[package]
name = "iproto"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = [
    "rt", "net", "sync", "io-util",
    "test-util", "macros", "time",
    "parking_lot",
] }
rmp-serde = "0.15"
serde = "1.0"
sharded-slab = "0.1"
rmp = "^0.8"
futures = "0.3"

[workspace]
members = ["bench"]

[profile.dev]
opt-level = 3
